export const snippets = [
  {
    id: 1,
    title: "Tribunal Regional do Trabalho da 2ª Região TRT-2 - ROT - Recurso Ordinário Trabalhista: ROT 1000692-38.2024.5.02.0073",
    meta: "Jurisprudência • Acórdão • publicado em 27/02/2025",
    ementa: "CARGO DE CONFIANÇA BANCÁRIO. ANALISTA. ATRIBUIÇÕES MERAMENTE TÉCNICAS. O cargo de confiança do bancário não se confunde com o preconizado no art. 62 , \" II \", da CLT . Embora o art. 224 , § 2º , da CLT não exija, para a caracterização do cargo de confiança do bancário, os mesmos elementos definidores do art. 62 , \" II \", há que ter o empregado certa autonomia em suas funções, que impliquem em algum poder de gestão e mando, situação não comprovada no caso dos autos. Não se pode concluir exercício de cargo de confiança apenas pela remuneração diferenciada do empregado, ou pagamento de gratificação, pois esta, no caso, remunera apenas o conhecimento técnico e a maior responsabilidade de cargo. Recurso ordinário do reclamado a que se nega provimento."
  },
  {
    id: 2,
    title: "Tribunal Regional do Trabalho da 2ª Região TRT-2 - AIRO - Agravo de Instrumento em Recurso Ordinário: AIRO 1000207-90.2024.5.02.0088",
    meta: "Jurisprudência • Acórdão • publicado em 27/02/2025",
    ementa: "CARGO DE CONFIANÇA BANCÁRIO. ANALISTA. ATRIBUIÇÕES MERAMENTE TÉCNICAS. O cargo de confiança do bancário não se confunde com o preconizado no art. 62 , \" II \", da CLT . Embora o art. 224 , § 2º , da CLT não exija, para a caracterização do cargo de confiança do bancário, os mesmos elementos definidores do art. 62 , \" II \", há que ter o empregado certa autonomia em suas funções, que impliquem em algum poder de gestão e mando, situação não comprovada no caso dos autos. Não se pode concluir exercício de cargo de confiança apenas pela remuneração diferenciada do empregado, ou pagamento de gratificação, pois esta, no caso, remunera apenas o conhecimento técnico e a maior responsabilidade de cargo. Recurso ordinário do reclamado a que se nega provimento."
  },
  {
    id: 3,
    title: "Tribunal Superior do Trabalho TST: Ag-RR 0000414-19.2017.5.20.0002",
    meta: "Jurisprudência • Acórdão • publicado em 11/02/2025",
    ementa: "AGRAVO. RECURSO DE REVISTA DA PARTE ADVERSA PROVIDO. HORAS EXTRAS. CARGO DE CONFIANÇA E GESTÃO. ART. 62 , II E PARÁGRAFO ÚNICO , DA CLT . RECEBIMENTO DE GRATIFICAÇÃO INFERIOR A 40% DO SALÁRIO EFETIVO. NÃO CUMPRIMENTO DO REQUISITO OBJETIVO. TRANSCENDÊNCIA RECONHECIDA. 1. Prevalece nesta Corte Superior o entendimento de que, para a configuração do exercício de cargo de gestão, excludente da percepção de horas extras, conforme previsto no art. 62 , II e parágrafo único, da CLT , é necessário a cumulação de dois requisitos, quais sejam o empregado deve possuir efetivos poderes de mando e gestão, de modo que suas funções representem grau de fidúcia especial, e o salário do cargo de confiança, compreendendo a gratificação de função, deve ser superior ao valor do respectivo salário efetivo, acrescido no mínimo de 40% (quarenta por cento). 2. Na hipótese dos autos, este último requisito objetivo não restou observado, conforme registrado pela Corte Regional. 3. No caso, extrai-se do quadro fático delineado pela Corte Regional, notadamente do voto vencido, que é parte integrante do acórdão para todos os fins legais ( CPC , art. 941 , § 3º ), que “ a soma do salário efetivo com a função gratificada não ultrapassa o salário efetivo acrescido de 40%, até porque a função gratificada de R$ 750,00, desde junho/2013, é inferior aos 40% do salário-base efetivo, estando ausente esse requisito, conforme se observa do contracheque de agosto/2013 (Id. a91fe60 - pág. 1), cujo salário-base é de R$ 5.763,00 e a Gratificação de Coordenador é de R$ 750,00 ”. 4. Assim, confirma-se a decisão agravada que, com suporte na jurisprudência do TST, deu provimento ao recurso de revista interposto pelo autor para, “reformando o acórdão recorrido, afastar o enquadramento da jornada de trabalho do autor na exceção do art. 62, II, da CLT e determinar o retorno dos autos ao Tribunal Regional de origem para o exame da pretensão deduzida em juízo, relacionada à jornada de trabalho (recebimento de horas extras, dobras, intervalo intrajornada e interjornada, sobreaviso, horas ‘in itinere’ e adicional noturno), como entender de direito.” Agravo a que se nega provimento ."
  },
  {
    id: 4,
    title: "Tribunal Superior do Trabalho TST: AIRR 1000742-66.2018.5.02.0205",
    meta: "Jurisprudência • Acórdão • publicado em 29/05/2024",
    ementa: "AGRAVO. AGRAVO DE INSTRUMENTO EM RECURSO DE REVISTA. PROCESSO SOB A ÉGIDE DAS LEIS 13.015 /2014 E 13.467 /2017. BANCÁRIO. CARGO DE CONFIANÇA. ART. 62 , II , DA CLT . NÃO CONFIGURAÇÃO. MATÉRIA FÁTICA. SÚMULAS 102, I/TST E 126/TST. O cargo de confiança recebeu explícita tipificação legal, quer no padrão amplo do art. 62 da CLT , quer no tipo jurídico específico bancário do art. 224 , § 2º , da Consolidação. Para que ocorra o enquadramento do empregado bancário nas disposições contidas no art. 224 , § 2º , da CLT , é necessário ficar comprovado, no caso concreto, que o empregado exercia efetivamente as funções aptas a caracterizarem o cargo de confiança e, ainda, que elas se revestiam de fidúcia especial, que extrapola aquela básica, inerente a qualquer empregado. É indispensável, ainda, o percebimento de gratificação igual ou superior a um terço do salário. Por outro lado, o enquadramento do bancário nas disposições do art. 62 , II , da CLT , além da fidúcia específica do art. 224 , § 2º , da CLT , pressupõe o exercício de cargo de gestão, que, nos termos da Súmula 287/TST, seriam aquelas atividades exercidas pelo gerente geral de agência ou outros cargos por equiparação. No caso concreto, o Tribunal Regional, amparado no conjunto probatório produzido nos autos, manteve a sentença que entendeu pelo enquadramento da Reclamante na hipótese do cargo de confiança do art. 224 , § 2º , da CLT , e não no do art. 62 , II , da CLT . Concluiu o Regional que “o conjunto fático-probatório revela de forma inequívoca que a autora não exercia cargo de confiança alegado pela defesa, de forma a inserir-se na excludente de que trata o inciso II, do art. 62, da CLT”. Diante do quadro fático explicitado na origem, para que se pudesse chegar, se fosse o caso, a conclusão fática diversa, seria necessário o revolvimento do conteúdo probatório constante dos autos, o que fica inviabilizado nesta instância recursal, nos termos das Súmulas 102, I e 126/TST. Assim sendo, a decisão agravada foi proferida em estrita observância às normas processuais (art. 557 , caput, do CPC/1973 ; arts. 14 e 932, IV, a, do CPC/2015), razão pela qual é insuscetível de reforma ou reconsideração. Agravo desprovido."
  },
  {
    id: 5,
    title: "Tribunal Regional do Trabalho da 9ª Região TRT-9 - RECURSO ORDINARIO TRABALHISTA: ROT 0000131-72.2017.5.09.0011",
    meta: "Jurisprudência • Acórdão • publicado em 08/03/2022",
    ementa: "REGIME DA DURAÇÃO DO TRABALHO. EXCLUSÃO. CARGO DE CONFIANÇA. REQUISITOS OBJETIVOS E SUBJETIVOS NÃO CONFIGURADOS. DIREITO A HORAS EXTRAS RECONHECIDO. Trabalhadores com cargo de confiança não são contemplados pelo regime da duração do trabalho, por força do art. 62, II da CLT. Eventual labor além da jornada normal, portanto, não será remunerado como hora extra. O exercício do cargo de confiança, todavia, pressupõe requisitos que a doutrina e a jurisprudência enquadram como objetivos e subjetivos. Entre os primeiros encontram-se: a) o pagamento de gratificação de função não inferior a 40% do salário; b) anotação do cargo e da gratificação correspondente na CTPS do trabalhador e no livro de registro de empregados. Os segundos exigem: a) investidura em poderes de mando, gestão e representação, de forma a configurar quase que o alter ego do empregador; e b) que o empregado usufrua da confiança máxima do empregador, a ponto de estar autorizado a comprometer o próprio negócio ou aspectos importantes dele. Ausentes os requisitos afasta-se o enquadramento e, confirmado o labor em sobrejornada, são devidas horas extras e reflexos. Recurso ordinário da ré a que se nega provimento neste particular."
  },
  {
    id: 6,
    title: "Tribunal Regional do Trabalho da 15ª Região TRT-15: ROT 0011112-21.2018.5.15.0089 0011112-21.2018.5.15.0089",
    meta: "Jurisprudência • Acórdão • publicado em 28/09/2020",
    ementa: "CARGO DE CONFIANÇA. NÃO CARACTERIZAÇÃO. HORAS EXTRAS. CABIMENTO. Não comprovados o exercício de atividades com poderes de mando e gestão relevantes dentro da estrutura organizacional da empresa e a percepção de gratificação específica do cargo de confiança, a inexistência de controle e fiscalização de jornada, por si só, não justifica o enquadramento do empregado na exceção prevista no art. 62, II, da CLT, sendo devido ao trabalhador o direito às horas extras laboradas e não quitadas."
  },
  {
    id: 7,
    title: "Tribunal Superior do Trabalho TST - RECURSO DE REVISTA: RR 0000343-19.2020.5.09.0325",
    meta: "Jurisprudência • Acórdão • publicado em 18/08/2023",
    ementa: "RECURSO DE REVISTA - HORAS EXTRAORDINÁRIAS ALÉM DA OITAVA DIÁRIA - AUSÊNCIA DOS PODERES DE GESTÃO A QUE SE REFERE O ART. 62, II, DA CLT . 1. O Tribunal Regional reformou a sentença em que se havia condenado os reclamados ao pagamento de diferenças decorrentes de horas extraordinárias por entender configurado o exercício de cargo de confiança (art. 62, II, da CLT). 2. Contudo, registrado no acórdão regional que o reclamante tinha que se reportar a superior hierárquico, não detinha poderes para contratar e demitir, e, ainda, recebia visitas da coordenadora, à qual precisava pedir autorização para se ausentar, não se verifica preenchido o requisito subjetivo do exercício do cargo de confiança, sendo assim devidas as horas extras correspondentes ao período. Recurso de revista conhecido e provido."
  },
  {
    id: 8,
    title: "Tribunal Regional do Trabalho da 2ª Região TRT-2: 1001373-23.2020.5.02.0081 SP",
    meta: "Jurisprudência • Acórdão • publicado em 14/07/2022",
    ementa: "EMENTA. CARGO DE CONFIANÇA BANCÁRIO. ESPECIALISTA EM INVESTIMENTOS. O cargo de confiança do bancário não se confunde com o preconizado no art. 62, \"II\", da CLT. Não há necessidade de deter poderes de verdadeiro mandatário, mas deverá possuir simples poderes de representação, circundados por outros elementos de convicção, como possuir subordinados e alguns poderes de direção administrativa dentro do setor onde opera, tais como distribuir-lhes tarefas, colocá-los à disposição de superiores hierárquicos, discipliná-los, fiscalizar-lhes a execução de serviços. Embora o artigo 224, § 2º, da CLT não exija, para a caracterização do cargo de confiança do bancário, os mesmos elementos definidores do art. 62, \"II\", há que ter o empregado certa autonomia em suas funções, que implique em algum poder de gestão e mando, situação não comprovada no caso dos autos. Não se pode concluir exercício de cargo de confiança apenas pela remuneração diferenciada do empregado, ou pagamento de gratificação, pois esta, no caso, remunera apenas o conhecimento técnico e a maior responsabilidade de cargo. Recurso Ordinário a que se nega provimento."
  }
];
